# Data Acquisition & Cleaning

```{r fetch-pse-data}
pal_raw <- read_csv("pal_stock.csv", show_col_types = FALSE) 

pal_df <- pal_raw %>%
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  
  filter(!is.na(Date)) %>%
  
  arrange(Date) %>%
  
  mutate(
    `Vol.` = case_when(
      str_detect(`Vol.`, "K") ~ as.numeric(str_remove(`Vol.`, "K")) * 1000,
      str_detect(`Vol.`, "M") ~ as.numeric(str_remove(`Vol.`, "M")) * 1000000,
      `Vol.` == "-" ~ 0,
      TRUE ~ as.numeric(`Vol.`)
    )
  ) %>%
  select(Date, Open, High, Low, Price, `Vol.`) %>% 
  rename(Close = Price, Volume = `Vol.`) %>%
  
  mutate(AdjClose = Close) 

pal_xts <- xts(pal_df[, -1], order.by = pal_df$Date)

colnames(pal_xts) <- c("PAL.Open", "PAL.High", "PAL.Low", "PAL.Close", "PAL.Volume", "PAL.Adjusted")

PAL <- pal_xts["2019-12/2025-12"]
```

```{r load-yahoo}
yahoo_tickers <- c(
  US_Equity = "UAL",     # US Equity: United Airlines
  Bitcoin = "BTC-USD",   # Bitcoin in USD
  SPY = "SPY",           # SPDR S&P 500 ETF Trust
  VIX = "^VIX"           # CBOE Volatility Index
)

getSymbols(yahoo_tickers, src = "yahoo", from = start_date, to = end_date)
```


```{r load-fred}
fred_tickers <- c(
  "DGS10",
  "FEDFUNDS",
  "CPIAUCSL"
)

getSymbols(fred_tickers, src = "FRED")

DGS10 <- window(DGS10, start = start_date, end = end_date)
FEDFUNDS <- window(FEDFUNDS, start = start_date, end = end_date)
CPIAUCSL <- window(CPIAUCSL, start = start_date, end = end_date)
```
```{r init-obs}
instruments <- c("UAL", "PAL", "BTC-USD", "SPY", "VIX", "DGS10", "FEDFUNDS", "CPIAUCSL")
init_obs <- function(ticker_list, sample_size = 3){
   for (sym in ticker_list) {
    data_obj <- get(sym)
    cat("INSTRUMENT:", sym, "\n")
    
    print(head(data_obj))
    cat("\n")
    
    na_indices <- which(rowSums(is.na(data_obj)) > 0)
    missing_count <- length(na_indices)
    
    cat("Total NAs:", missing_count, "\n\n")
    if (missing_count > 0) {
      for (idx in head(na_indices, sample_size)) {
        start_idx <- max(1, idx - 1)
        end_idx <- min(nrow(data_obj), idx + 1)
        print(data_obj[start_idx:end_idx, ])
        cat("------\n")
      }
      cat("\n")
    }
    
    dup_indices <- which(duplicated(zoo::index(data_obj)))
    dup_count <- length(dup_indices)
    cat("Total Duplicates:", dup_count, "\n\n")
    
    if (dup_count > 0) {
      for (idx in head(dup_indices, sample_size)) {
        start_idx <- max(1, idx - 1)
        end_idx <- min(nrow(data_obj), idx + 1)
        
        print(data_obj[start_idx:end_idx, ])
        cat("------\n")
      }
      cat("\n")
    }
  } 
}
init_obs(instruments)
```

```{r fix-local-na}
for (sym in instruments) {
  temp_data <- get(sym)
  temp_data <- na.locf(temp_data)
  assign(sym, temp_data)
}
```

```{r check-local-na-fix}
init_obs(instruments)
```
