# Data Integration

Get a list of tibble objects from the raw financial instruments data.

That is: `UAL.Adjusted`, `PAL.Adjusted`, `BTC-USD.Adjusted`, `SPY.Adjusted`, `VIX.Adjusted`, `DGS10`, `FEDFUNDS`, `CPIAUCSL`, `DGS2`
```{r convert-to-df}
df_list <- map(instruments, function(sym) {
  data_obj <- get(sym)
  
  # If it has an Adjusted column, extract it. Otherwise, use the raw data object.
  if (has.Ad(data_obj)) {
    extracted_data <- Ad(data_obj)
  } else {
    extracted_data <- data_obj
  }
  
  clean_df <- as.data.frame(extracted_data) %>% 
    rownames_to_column(var = "Date") %>% 
    mutate(Date = as.Date(Date)) %>%
    as_tibble()
  
  return(clean_df)
})

df_list
```

Create a compact Master Data frame tibble full join on date.
```{r to-master-df}
master_df <- df_list %>% 
  compact() %>%                       # Remove full NA rows
  reduce(full_join, by = "Date") %>%  # Full Join
  arrange(Date) %>%                   # Arrange by date
  fill(-Date, .direction = "down")    # Forward fill

master_df
```

Get the log returns of each asset
```{r log-returns}
# Get Log Adjusted (Difference of Logs) from tickers with adjusted price. 
adjusted_cols <- names(master_df)[str_detect(names(master_df), "\\.Adjusted$")]
master_df <- master_df %>%
  # Mutate only calculate log returns on columns that end in ".Adjusted"
  # This automatically ignores DGS10, DGS2, FEDFUNDS, and CPIAUCSL
  mutate(
    across(
      all_of(adjusted_cols),
      ~ c(NA, diff(log(.x))),
      .names = "{str_remove(.col, '\\\\.Adjusted')}.LogAdj"
    )
  ) %>%
  select(-all_of(setdiff(adjusted_cols, "VIX.Adjusted")))

master_df
```

Exploring Missing rows
```{r explore-master-df}
explore_instruments <- function(instruments, master_df) {
  for (sym in instruments) {
    cat("INSTRUMENT:", sym, "\n")
    
    instrument_df <- master_df %>% 
      select(Date, starts_with(sym))
    
    print(instrument_df, n = 6)
    cat("\n")
    
    cat("--- Missing Values per Column ---\n")
    instrument_df %>% 
      summarise(across(everything(), ~sum(is.na(.)))) %>% 
      print(width = Inf)
    cat("\n")
    
    missing_rows <- instrument_df %>%
      filter(if_any(starts_with(sym), is.na))
    
    total_missing <- nrow(missing_rows)
    cat("Total Rows with NAs:", total_missing, "\n")
    
    if (total_missing > 0) {
      cat("--- Top 10 Missing Rows ---\n")
      print(missing_rows, n = 10)
    }
    
    dup_count <- sum(duplicated(instrument_df$Date))
  }
  
  dplyr::glimpse(master_df)
}

explore_instruments(instruments, master_df)
```


```{r fix-missing-master-df}
master_df <- master_df %>%
  fill(-Date, .direction = "down") %>%
  filter(Date >= as.Date("2020-01-01"))

explore_instruments(instruments, master_df)
```















